env:
  browser: true
  es2021: true
extends: 
 - airbnb-base
 - plugin:import/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
rules: 
  semi:
    - error
    - always
  quotes:
    - error
    - single
  no-underscore-dangle: off
  comma-dangle:
    - error
    - always-multiline
  import/extensions: off
  no-param-reassign:
    - error
    -
      props: false
  lines-between-class-members:
    - error
    - always
    -
      exceptAfterSingleLine: true
  no-unused-vars: warn
